myshop/urls.py
from django.contrib.auth.forms import AuthenticationForm
from django.utils import html
from myshop.forms import LoginForm
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .forms import LoginForm, MyPasswordChangeForm, MyPasswordResetForm, MySetPasswordForm
from django.contrib.auth import views as auth_views

urlpatterns = [

    path('', views.Home, name='home'),

    path('category/<int:id>/products', views.Categories, name='category'),

    path('all-category-products/', views.Allcategories, name='all_category'),

    path('product-detail/<int:id>/', views.ProductDetail, name='product_detail'),

    path('profile/', views.MyProfile.as_view(), name='profile'),

    path('search/', views.Search, name='search'),

    path('review/', views.Review_rate, name='review'),

    path('add-to-cart/', views.Add_to_cart, name='add_to_cart'),

    path('cart-item/', views.CartItem, name='cart_item'),

    path('buyNow/', views.BuyNow, name='buyNow'),

    path('checkout/', views.Checkout.as_view(), name='checkout'),

    path('orders/', views.Orders, name='orders'),

    path('plus_minus_item/', views.Plus_Minus_Item,
         name='plus_minus_item'),

    path('registration/', views.CustomerRegistration.as_view(),
         name='customerregistration'),

    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html',
                                                         authentication_form=LoginForm), name='login'),

    path('password-change/', auth_views.PasswordChangeView.as_view(template_name='password_change.html',
                                                                   form_class=MyPasswordChangeForm, success_url='/password-change-done/'), name='password_change'),

    path('password-change-done/', auth_views.PasswordResetView.as_view(template_name='password_change_done.html'),
         name='password_change_done'),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html',
                                                                 form_class=MyPasswordResetForm), name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'), name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html', form_class=MySetPasswordForm), name='password_reset_confirm'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),

    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoppingcart/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myshop.urls')),
]

myshop/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from multiselectfield import MultiSelectField

STATE_CHOICES = (
    ("Andhra Pradesh", "Andhra Pradesh"),
    ("Arunachal Pradesh ", "Arunachal Pradesh "),
    ("Assam", "Assam"),
    ("Bihar", "Bihar"),
    ("Chandigarh", "Chandigarh"),
    ("Chhattisgarh", "Chhattisgarh"),
    ("Delhi", "Delhi"),
    ("Daman and Diu", "Daman and Diu"),
    ("Dadra and Nagar Haveli", "Dadra and Nagar Haveli"),
    ("Goa", "Goa"),
    ("Gujarat", "Gujarat"),
    ("Haryana", "Haryana"),
    ("Himachal Pradesh", "Himachal Pradesh"),
    ("Jammu and Kashmir ", "Jammu and Kashmir "),
    ("Jharkhand", "Jharkhand"),
    ("Karnataka", "Karnataka"),
    ("Kerala", "Kerala"),
    ("Lakshadweep", "Lakshadweep"),
    ("Madhya Pradesh", "Madhya Pradesh"),
    ("Maharashtra", "Maharashtra"),
    ("Manipur", "Manipur"),
    ("Meghalaya", "Meghalaya"),
    ("Mizoram", "Mizoram"),
    ("Nagaland", "Nagaland"),
    ("Odisha", "Odisha"),
    ("Punjab", "Punjab"),
    ("Puducherry", "Puducherry"),
    ("Rajasthan", "Rajasthan"),
    ("Sikkim", "Sikkim"),
    ("Tamil Nadu", "Tamil Nadu"),
    ("Telangana", "Telangana"),
    ("Tripura", "Tripura"),
    ("Uttar Pradesh", "Uttar Pradesh"),
    ("Uttarakhand", "Uttarakhand"),
    ("West Bengal", "West Bengal"),
    ("Andaman and Nicobar Islands", "Andaman and Nicobar Islands"),
)

SIZE_CHOICES = (
    ('S', 'S'),
    ('M', 'M'),
    ('L', 'L'),
    ('XL', 'XL'),
    ('XXL', 'XXL'),
)

STATUS_CHOICES = (
    ('Accepted', 'Accepted'),
    ('Packed', 'Packed'),
    ('On The Way', 'On The Way'),
    ('Delivered', 'Delivered'),
    ('Cancelled', 'Cancelled'),
)

LABEL_CHOICES = (
    ('New', 'new'),
    ('Bestseller', 'bestseller'),
)

LABEL_COLOR_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
)

PAYMENT_OPTION_CHOICES = (
    ('Stripe', 'Stripe'),
    ('Paypal', 'Paypal'),
    ('Cash on delivery', 'Cash on delivery'),
)


class Carousel(models.Model):
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return str(self.id)


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile_no = models.IntegerField(null=True)
    address1 = models.CharField(max_length=200, null=True)
    address2 = models.CharField(max_length=200, blank=True, null=True)
    city = models.CharField(max_length=50, null=True)
    state = models.CharField(
        max_length=70, choices=STATE_CHOICES, null=True)
    zip_code = models.PositiveIntegerField(null=True)
    profile_image = models.ImageField(
        upload_to='images', default='images/user1.jpg', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.profile_image.path)

        if img.width > 150 or img.height > 150:
            new_img = (150, 150)
            img.thumbnail(new_img)
            img.save(self.profile_image.path)


class Category(models.Model):
    category = models.CharField(max_length=15)

    def __str__(self):
        return self.category


class Product(models.Model):
    title = models.CharField(max_length=100)
    price = models.IntegerField()
    discounted_price = models.IntegerField(blank=True, null=True)
    description = models.TextField()
    tag = models.CharField(choices=LABEL_CHOICES,
                           max_length=15, blank=True, null=True)
    label = models.CharField(choices=LABEL_COLOR_CHOICES,
                             max_length=1, blank=True, null=True)
    brand = models.CharField(max_length=50)
    size = MultiSelectField(choices=SIZE_CHOICES, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)

        if img.width > 300 or img.height > 300:
            new_img = (300, 300)
            img.thumbnail(new_img)
            img.save(self.image.path)


class Product_Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return str(self.product.title)


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    prod_size = models.CharField(max_length=4, blank=True, null=True)

    def __str__(self):
        return str(self.product)


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    customer = models.ForeignKey(
        Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    size = models.CharField(max_length=3, blank=True, null=True)
    payment_option = models.CharField(
        max_length=50, choices=PAYMENT_OPTION_CHOICES, null=True)
    ordered_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=50, choices=STATUS_CHOICES, default='Pending')

    def __str__(self):
        return str(self.id)

    @property
    def total_cost_of_product(self):
        if self.product.discounted_price:
            item_cost = self.product.discounted_price
        else:
            item_cost = self.product.price
        return self.quantity * item_cost


class Review(models.Model):
    user = models.ForeignKey(User, models.CASCADE)
    product = models.ForeignKey(Product, models.CASCADE)
    comment = models.TextField(max_length=250)
    rate = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

myshop/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from django.forms import fields, models, widgets
from django.utils.translation import gettext, gettext_lazy as _
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth import password_validation
from .models import Customer, Order


class CustomerRegistrationForm(UserCreationForm):
    email = forms.CharField(required=True, widget=forms.EmailInput
                            (attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput
                                (attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Confirm Password (again)', widget=forms.PasswordInput
                                (attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        lables = {'email': 'Email'}
        widgets = {'username': forms.TextInput(
            attrs={'class': 'form-control'})}

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                'A user with that email already exists.')
        return email


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput
                             (attrs={'autofocus': True, 'class': 'form-control'}))
    password = forms.CharField(label=_("Password"), strip=False, widget=forms.PasswordInput
                               (attrs={'autocomplete': 'current-password', 'class': 'form-control'}))


class MyPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label=_("Old Password"), strip=False, widget=forms.PasswordInput
                                   (attrs={'autofocus': True, 'autocomplete': 'current-password', 'class': 'form-control'}))
    new_password1 = forms.CharField(label=_("New Password"), strip=False, widget=forms.PasswordInput
                                    (attrs={'autocomplete': 'new-password', 'class': 'form-control'}), help_text=password_validation.
                                    password_validators_help_text_html())
    new_password2 = forms.CharField(label=_("Confirm New Password"), strip=False, widget=forms.PasswordInput
                                    (attrs={'autocomplete': 'new-password', 'class': 'form-control'}))


class MyPasswordResetForm(PasswordResetForm):

    email = forms.CharField(label=_("Email"), max_length=254, widget=forms.EmailInput
                                   (attrs={'autofocus': True, 'autocomplete': 'email', 'class': 'form-control'}))


class MySetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label=_("New Password"), strip=False, widget=forms.PasswordInput
                                    (attrs={'autofocus': True, 'autocomplete': 'new-password', 'class': 'form-control'}), help_text=password_validation.
                                    password_validators_help_text_html())
    new_password2 = forms.CharField(label=_("Confirm New Password"), strip=False, widget=forms.PasswordInput
                                    (attrs={'autocomplete': 'new-password', 'class': 'form-control'}))


class MyUserProfileForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        widgets = {'username': forms.TextInput(
            attrs={'placeholder': 'Username', 'autofocus': True, 'class': 'form-control'}), 'first_name': forms.TextInput(
            attrs={'placeholder': 'First Name', 'class': 'form-control'}), 'last_name': forms.TextInput(
            attrs={'placeholder': 'Last Name', 'class': 'form-control'}), 'email': forms.EmailInput(
            attrs={'placeholder': 'Email', 'class': 'form-control'})}


class MyProfileForm(forms.ModelForm):
    mobile_no = forms.CharField(label=_("Mobile number"), widget=forms.NumberInput
                                (attrs={'placeholder': 'Mobile No.', 'autocomplete': 'mobile_no', 'class': 'form-control'}))

    address1 = forms.CharField(label=_("Address"), widget=forms.TextInput
                               (attrs={'placeholder': '(Flat no. & Address)', 'autocomplete': 'address1', 'class': 'form-control'}))

    address2 = forms.CharField(label=_("Address 2 (optional)"), widget=forms.TextInput
                               (attrs={'placeholder': '(Landmark, Near by)', 'autocomplete': 'address2', 'class': 'form-control'}))

    city = forms.CharField(label=_("City"), widget=forms.TextInput
                           (attrs={'placeholder': 'City', 'autocomplete': 'city', 'class': 'form-control'}))

    zip_code = forms.CharField(label=_("Zip code"), widget=forms.NumberInput
                               (attrs={'placeholder': 'Pin code / Zip code', 'autocomplete': 'zip_code', 'class': 'form-control'}))

    class Meta:
        model = Customer
        fields = ['mobile_no', 'address1', 'address2',
                  'city', 'state', 'zip_code', 'profile_image']
        widgets = {'state': forms.Select(
            attrs={'class': 'form-control'})}


class MyUserCheckoutForm(forms.ModelForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ['first_name', 'last_name']
        widgets = {'first_name': forms.TextInput(
            attrs={'placeholder': 'First Name', 'class': 'form-control'}), 'last_name': forms.TextInput(
            attrs={'placeholder': 'Last Name', 'class': 'form-control'})}


class MyCheckoutForm(forms.ModelForm):
    mobile_no = forms.CharField(label=_("Mobile number"), widget=forms.NumberInput
                                (attrs={'placeholder': 'Mobile No.', 'autocomplete': 'mobile_no', 'class': 'form-control'}))

    address1 = forms.CharField(label=_("Address"), widget=forms.TextInput
                               (attrs={'placeholder': '(Flat no. & Address)', 'autocomplete': 'address1', 'class': 'form-control'}))

    address2 = forms.CharField(label=_("Address 2 (optional)"), widget=forms.TextInput
                               (attrs={'placeholder': '(Landmark, Near by)', 'autocomplete': 'address2', 'class': 'form-control'}))

    city = forms.CharField(label=_("City"), widget=forms.TextInput
                           (attrs={'placeholder': 'City', 'autocomplete': 'city', 'class': 'form-control'}))

    zip_code = forms.CharField(label=_("Zip code"), widget=forms.NumberInput
                               (attrs={'placeholder': 'Pin code / Zip code', 'autocomplete': 'zip_code', 'class': 'form-control'}))

    class Meta:
        model = Customer
        fields = ['mobile_no', 'address1', 'address2',
                  'city', 'state', 'zip_code']
        widgets = {'state': forms.Select(
            attrs={'class': 'form-control'})}


PAYMENT_OPTION_CHOICES = (
    ('Stripe', 'Stripe'),
    ('Paypal', 'Paypal'),
    ('Cash on delivery', 'Cash on delivery'),
)


class PaymentOptionForm(forms.ModelForm):
    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT_OPTION_CHOICES)

    class Meta:
        model = Order
        fields = ['payment_option']

myshop/templates/allcategories.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% block content %}

{% if all_product %}
<div class="row" id="tablesectionrow">
    <aside class="text-center" id="categoriestable">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Categories</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <a href="{% url 'all_category' %}">All</a>
                    </td>
                </tr>
                {% for category in categories %}
                <tr>
                    <td>
                        <a href="{% url 'category' category.id %}">{{ category }}</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </aside>
    <!--Section: Products v.3-->
    <section class="text-center mb-4" id="categoriessection">
        <!--Grid row-->
        <div class="row wow fadeIn">
            {% for prod in all_product %}
            <!--Grid column-->
            <div class="col-lg-3 col-md-6 mb-4">
                 <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="{{ prod.image.url }}" class="card-img-top" height="300" alt="">

                <a href="{% url 'product_detail' prod.id %}" class="card-block clearfix">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="{% url 'product_detail' prod.id %}" class="grey-text">
                  <h5>{{ prod.category }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{% url 'product_detail' prod.id %}" class="dark-grey-text">{{ prod.title }}
                {% if prod.label %}
                   <span class="badge badge-pill {{ prod.get_label_display }}-color ml-1">{{prod.tag}}</span>
                {% endif %}
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                {% if prod.discounted_price %}
                  <strong><i class="fa mr-1" style="font-size: 20px;">&#xf156;</i>{{ prod.discounted_price|intcomma }}</strong>
                {% else %}
                  <strong><i class="fa mr-1" style="font-size: 20px;">&#xf156;</i>{{ prod.price|intcomma }}</strong>
                {% endif %}  
                </h4>
              </div>
              <!--Card content-->

            </div>
            <!--Card-->

            </div>
            <!--Grid column-->
            {% endfor %}
        </div>
        <!--Fourth column-->
</div>
<!--Grid row-->
</section>
<!--Section: Products v.3-->
</div>
<!--Pagination-->
<nav class="d-flex justify-content-center wow fadeIn">
    <ul class="pagination pg-blue">
        <!--Arrow left-->
        {% if all_product.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{all_product.previous_page_number}}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}

        {% for pg in all_product.paginator.page_range %}
        {% if all_product.number == pg %}
        <li class="page-item active">
            <a class="page-link" href="?page={{pg}}" class="btn btn-default">{{pg}}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{pg}}" class="btn">{{pg}}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if all_product.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{all_product.next_page_number}}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
<!--Pagination-->

{% else %}

<div class="text-center" style="margin-top: 150px; margin-bottom: 256px;">
    <h1>Sorry, Cann't load this page !!</h1><br>
    <h2>"products not found"</h2>
</div>

{% endif %}

{% endblock %}

myshop/templates/categories.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% block content %}

{% if product %}
<div class="row" id="tablesectionrow">
<aside class="text-center" id="categoriestable">
<table class="table table-bordered">
<thead>
<tr>
<th>Categories</th>
</tr>
</thead>
<tbody>
<tr>
    <td><a href="{% url 'all_category' %}">All</a></td>
</tr>
  
    {% for category in categories %}
  <tr>
    <td><a href="{% url 'category' category.id %}">{{ category }}</a></td>
  </tr>
   
    {% endfor %}

</tbody>
</table>
</aside>

       <!--Section: Products v.3-->
      <section class="text-center mb-4" id="categoriessection">

        <!--Grid row-->
        <div class="row wow fadeIn">
            {% for prod in product %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="{{ prod.image.url }}" class="card-img-top" height="300" alt="">

                <a href="{% url 'product_detail' prod.id %}" class="card-block clearfix">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="{% url 'product_detail' prod.id %}" class="grey-text">
                  <h5>{{ prod.category }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{% url 'product_detail' prod.id %}" class="dark-grey-text">{{ prod.title }}
                {% if prod.label %}
                   <span class="badge badge-pill {{ prod.get_label_display }}-color ml-1">{{prod.tag}}</span>
                {% endif %}
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                {% if prod.discounted_price %}
                  <strong><i class="fa mr-1" style="font-size: 20px;">&#xf156;</i>{{ prod.discounted_price|intcomma }}</strong>
                {% else %}
                  <strong><i class="fa mr-1" style="font-size: 20px;">&#xf156;</i>{{ prod.price|intcomma }}</strong>
                {% endif %}  
                </h4>
              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->

            {% endfor %}
          </div>
          <!--Fourth column-->

        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

</div>

 <!--Pagination-->
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {% if product.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{product.previous_page_number}}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          {% for pg in product.paginator.page_range %}
            {% if product.number == pg %}

            <li class="page-item active"><a class="page-link" href="?page={{pg}}" class="btn btn-default">{{pg}}</a>
            </li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{pg}}" class="btn">{{pg}}</a></li>
               
            {% endif %}
          {% endfor %}
 
          {% if product.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{product.next_page_number}}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      <!--Pagination-->

{% else %}

<div class="text-center" style="margin-top: 150px; margin-bottom: 256px;">
    <h1>Sorry, Cann't load this page !!</h1><br>
    <h2>"products not found"</h2>
</div>

{% endif %}

{% endblock %}

myshop/templates/empty_cart.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container" style="margin-top: 120px;">
    <div class="row">
    <h3 class="text-center mb-5 w-100" style="font-weight:500;">Sorry, Cann't load this page !!</h3>
        <div class="text-center" style="margin-left:37%; margin-right:37%;">
            <img src="{% static 'img/empty_cart.gif' %}" alt="" class="img-fluid" />
        </div>
    </div
</div>

{% endblock %}

myshop/templates/search.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% block home %} active {% endblock home %}

{% block content %}

  <!--Main layout-->
  <main style="word-wrap: break-word;">
    <div class="container" style="margin-top: 100px;">
    {% if messages %}
      {% for message in messages %}
      <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}</p>
      {% endfor %}
    {% endif %}

      <h1 class="my-4"><strong>Search Results:</strong></h1>
      {% if product|length < 1 %}
      Your search - <b>{{query}}</b> - did not match any documents.<br><br>

      Suggestions:
      <ul>
        <li>Make sure that all words are spelled correctly.</li>
        <li>Make sure that your query contains few words.</li>
        <li>Try different keywords.</li>
        <li>Try more general keywords.</li>
        <li>Try fewer keywords.</li>
      </ul>
      {% endif %}

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->

        <div class="row wow fadeIn">

          {% for prod in product %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="{{ prod.image.url }}" class="card-img-top" height="300" alt="">

                <a href="{% url 'product_detail' prod.id %}" class="card-block clearfix">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="{% url 'product_detail' prod.id %}" class="grey-text">
                  <h5>{{ prod.category }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{% url 'product_detail' prod.id %}" class="dark-grey-text">{{ prod.title }}
                {% if prod.label %}
                   <span class="badge badge-pill {{ prod.get_label_display }}-color ml-1">{{prod.tag}}</span>
                {% endif %}
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                {% if prod.discounted_price %}
                  <strong><i class="fa mr-1" style="font-size: 18px;">&#xf156;</i>{{ prod.discounted_price|intcomma }}</strong>
                {% else %}
                  <strong><i class="fa mr-1" style="font-size: 18px;">&#xf156;</i>{{ prod.price|intcomma }}</strong>
                {% endif %}  
                </h4>
              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->

          {% endfor %}
        </div>
        <!--Fourth column-->
    </div>
    <!--Grid row-->

    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        <!--Arrow left-->
        {% if product.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{product.previous_page_number}}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        {% for pg in product.paginator.page_range %}
        {% if product.number == pg %}

        <li class="page-item active"><a class="page-link" href="?page={{pg}}" class="btn btn-default">{{pg}}</a>
        </li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{pg}}" class="btn">{{pg}}</a></li>

        {% endif %}
        {% endfor %}

        {% if product.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{product.next_page_number}}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    <!--Pagination-->

</div>
</main>
<!--Main layout-->


{% endblock %}